### ISSUE TITLE
Bug in the UT-13 fixed version

### ISSUE THREAD

**Issue by yarinamomo** [ForeverZyh/TensorFlow-Program-Bugs#5]
Hi,

In the StackOverflow/UT-10/36343542-fix/tflin.py, I think there is a bug even though the script is marked as fixed. 

Specifically, on line 60: 
 `cost = tf.reduce_sum(tf.pow(activation - Y, 2)) / (2 * n_samples)`

and line 87: 
 `testing_cost = sess.run(tf.reduce_sum(tf.pow(activation - Y, 2)) / (2 * test_X.shape[0]), feed_dict={X: test_X, Y: test_Y})`
                              
`activation` is of shape `[None, 1]` and `Y` is of shape `[None]`, the subtraction of `activation` and `Y` will be `[None, None]` (`Y` will be broadcasted to `[None,None]`), where `None` is the batch size.

However, `Y` should be of shape `[None, 1]`, and no need for broadcasting. Because the cost function aims to calculate the squared errors, intending to measure the difference between the predicted `Y` (denoted as `activation` in the code) and the actual `Y`.

It can be fixed by changing the two lines to:
`cost = tf.reduce_sum(tf.pow(activation - Y[...,numpy.newaxis], 2)) / (2 * n_samples)`

and
`testing_cost = sess.run(tf.reduce_sum(tf.pow(activation - Y[...,numpy.newaxis], 2)) / (2 * test_X.shape[0]), feed_dict={X: test_X, Y: test_Y})`

without changing anything else. This does not crash the program, but it is a logical error that outputs the wrong cost value (for the whole dataset - train and test datasets). For the training process, it is correct because the data was fed one by one.

**Comment by ForeverZyh** [comment]
You are right about the broadcasting issue. I think a better fix is to 
1. Change `Y = tf.placeholder(tf.float32, [None])` to `Y = tf.placeholder(tf.float32, [None, 1])`, 
2. When passing `feed_dict`, we create a new dimension for `test_Y` or `train_Y` each time.
I am actually not sure that your fix would work by create a new dimension by using `numpy.newaxis` on a TensorFlow Tensor.

Again, the repo is collected based on the stackoverflow best answer, so there is a chance that a "fixed" program still contains bugs.
